vida_mais_facil/portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cadastra_user, name='cadastra-user'),
    path('cadastrasaude/', views.cadastra_saude, name='cadastra-saude'),
    path('login/', views.login_user, name='login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('novo/', views.nova_consulta, name='nova-consulta'),
    path('editar/<int:id>/', views.editar_consulta, name='editar'),
    path('deletar/<int:id>/', views.deletar_consulta, name='deletar'),
]

vida_mais_facil/vida_mais_facil/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("portal.urls")),
]

vida_mais_facil/portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser

class RegistroSaude(models.Model):
    data_registro = models.DateTimeField(auto_now=True)
    f_cardiaca = models.IntegerField(verbose_name='Frequência Cardíaca', blank=True, null=True)
    glicemia = models.IntegerField(blank=True, null=True)
    peso = models.FloatField(blank=True, null=True)
    p_sistolica = models.IntegerField(blank=True, null=True, verbose_name='Pressão Sistolica')
    p_diastolica = models.IntegerField(blank=True, null=True, verbose_name='Pressão Diastolica')

class User(AbstractBaseUser):
    SEX = [
        ('masculino', 'Masculino'),
        ('feminino', 'Feminino'),
        ('outro', 'Outro'),
    ]

    cpf = models.CharField(max_length=11, unique=True, verbose_name='CPF')
    # Campo 'Password' já vem por padrão
    p_nome = models.CharField(max_length=64, verbose_name='Primeiro Nome')
    sobrenome = models.CharField(max_length=64)
    sexo = models.CharField(choices=SEX)
    foto_perfil = models.ImageField(upload_to='perfis/', default='default.jpg')
    saude = models.ForeignKey(RegistroSaude, on_delete=models.CASCADE, blank=True, null=True)
    rua = models.CharField(max_length=255)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=255)
    
    USERNAME_FIELD = 'cpf'
    REQUIRED_FIELDS = ['p_nome']

class Atendimento(models.Model):
    EMERGENCIA = [
        ('baixa', 'Baixa'),
        ('media', 'Média'),
        ('alta', 'Alta'),
        ('urgente', 'Urgente'),
    ]

    STATUS = [
        ('solicitado', 'Solicitado'),
        ('concluido', 'Concluido'),
    ]

    HORA = [
        ('08:00', '08:00'),
        ('09:00', '09:00'),
        ('10:00', '10:00'),
        ('11:00', '11:00'),
        ('14:00', '14:00'),
        ('15:00', '15:00'),
        ('16:00', '16:00'),
        ('17:00', '17:00'),
    ]

    MEDICO = [
        ('dr-joao', 'Dr. João Silva'),
        ('dra-maria', 'Dra. Maria Santos'),
        ('dr-pedro', 'Dr. Pedro Costa'),
        ('dra-ana', 'Dra. Ana Lima')
    ]

    ESPECIALIDADE = [
        ('cardiologia', 'Cardiologia'),
        ('geriatria', 'Geriatria'),
        ('clinicogeral', 'Clínico Geral'),
        ('oftalmologia', 'Oftalmologia'),
    ]
    
    medico = models.CharField(choices=MEDICO)
    especialidade = models.CharField(choices=ESPECIALIDADE, null=True, blank=True)
    titulo = models.CharField(max_length=255)
    observacao = models.TextField(null=True, blank=True)
    emergencia = models.CharField(choices=EMERGENCIA, default='Baixa')
    status =  models.CharField(choices=STATUS, default='Solicitado')
    data_solicitacao = models.DateField(auto_now=True)
    data_agendamento = models.DateField()
    hora_agendamento = models.CharField(choices=HORA)

vida_mais_facil/portal/forms.py
from django import forms
from .models import *

class CadastraUser(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'cpf',
            'password',
            'p_nome',
            'sobrenome',
            'sexo',
            'foto_perfil',
            'rua',
            'numero',
            'bairro',
        ]
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user
    
class CadastraSaude(forms.ModelForm):
    class Meta:
        model = RegistroSaude
        fields = [
            'f_cardiaca',
            'glicemia',
            'peso',
            'p_sistolica',
            'p_diastolica'
        ]

class LoginForm(forms.Form):
    cpf = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

class AtendimentoForm(forms.ModelForm):
    class Meta:
        model = Atendimento
        fields = [
            'medico',
            'especialidade',
            'titulo',
            'observacao',
            'emergencia',
            'status',
            'data_agendamento',
            'hora_agendamento',
        ]


"""
solicitante = models.ForeignKey(User, on_delete=models.CASCADE)
    medico = models.CharField(choices=MEDICO)
    especialidade = models.CharField(choices=ESPECIALIDADE, null=True, blank=True)
    titulo = models.CharField(max_length=255)
    observacao = models.TextField(null=True, blank=True)
    emergencia = models.CharField(choices=EMERGENCIA, default='Baixa')
    status =  models.CharField(choices=STATUS, default='Solicitado')
    data_solicitacao = models.DateField(auto_now=True)
    data_agendamento = models.DateField()
    hora_agendamento = models.CharField(choices=HORA)


"""

vida_mais_facil/portal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib import messages
from .models import *
from .forms import *
from .utils import autentica_manual

def cadastra_user(request):
    if request.method == 'POST':
        form = CadastraUser(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('cadastra-saude')
    else:
        form = CadastraUser()

    context = {'form': form}
    return render(request, 'cadastra-user.html', context)

def cadastra_saude(request):
    if request.method == 'POST':
        form = CadastraSaude(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = CadastraSaude()

    context = {'form': form}
    return render(request, 'cadastra-saude.html', context)

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cpf = form.cleaned_data['cpf']
            password = form.cleaned_data['password']
            user = autentica_manual(cpf, password)
            if user:
                auth_login(request, user)
                return redirect('dashboard')
            else:
                messages.error(request, "CPF ou Senha Inválidos!")
    else:
        form = LoginForm()

    context = {'form': form}
    return render(request, 'login.html', context)

def dashboard(request):
    atendimentos = Atendimento.objects.all()
    context = {'atendimentos': atendimentos}
    return render(request, 'dashboard.html', context)

def visualizar_saude(request):
    registros = RegistroSaude.objects.all()
    context = {'registros': registros}
    return render(request, 'saude.html', context)

def nova_consulta(request):
    form = AtendimentoForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('dashboard')

    context = {'form': form}
    return render(request, 'nova_consulta.html', context)

def deletar_consulta(request, id):
    atendimento = get_object_or_404(Atendimento, id=id)
    if request.method == 'POST':
        atendimento.delete()
        return redirect('dashboard')

    context = {'atendimento': atendimento}
    return render(request, 'deleta_consulta.html', context)

def editar_consulta(request, id):
    atendimento = get_object_or_404(Atendimento, id=id)
    if request.method == 'POST':
        form = AtendimentoForm(request.POST, instance=atendimento)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = AtendimentoForm(instance=atendimento)
    
    context = {'form': form}
    return render(request, 'nova_consulta.html', context)

vida_mais_facil/portal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard | Vida + Fácil</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <section class="sidebar">
        <div class="logo">
            <img src="{% static 'img/logo.png' %}" alt="">
        </div>
        <nav class="navbar">
            <ul>
                <li><a href="{% url 'dashboard' %}">
                <svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="M10.55 2.532a2.25 2.25 0 0 1 2.9 0l6.75 5.692c.507.428.8 1.057.8 1.72v9.803a1.75 1.75 0 0 1-1.75 1.75h-3.5a1.75 1.75 0 0 1-1.75-1.75v-5.5a.25.25 0 0 0-.25-.25h-3.5a.25.25 0 0 0-.25.25v5.5a1.75 1.75 0 0 1-1.75 1.75h-3.5A1.75 1.75 0 0 1 3 19.747V9.944c0-.663.293-1.292.8-1.72l6.75-5.692Zm1.933 1.147a.75.75 0 0 0-.966 0L4.767 9.37a.75.75 0 0 0-.267.573v9.803c0 .138.112.25.25.25h3.5a.25.25 0 0 0 .25-.25v-5.5c0-.967.784-1.75 1.75-1.75h3.5c.966 0 1.75.783 1.75 1.75v5.5c0 .138.112.25.25.25h3.5a.25.25 0 0 0 .25-.25V9.944a.75.75 0 0 0-.267-.573l-6.75-5.692Z" fill="#000000"/>
                </svg>Dashboard</a>
                </li>
                <li><a href="{% url 'nova-consulta' %}">
                    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2Zm0 1.5a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17ZM12 7a.75.75 0 0 1 .75.75v3.5h3.5a.75.75 0 0 1 0 1.5h-3.5v3.5a.75.75 0 0 1-1.5 0v-3.5h-3.5a.75.75 0 0 1 0-1.5h3.5v-3.5A.75.75 0 0 1 12 7Z" fill="#000000"/>
                    </svg>Nova Consulta</a>
                </li>
                <li><a href="">
                <svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path d="m12.82 5.58-.82.822-.824-.824A5.375 5.375 0 0 0 2.249 11h1.605a3.876 3.876 0 0 1 6.261-4.36l1.358 1.357a.75.75 0 0 0 1.073-.012L13.88 6.64A3.88 3.88 0 0 1 20.149 11h1.605a5.38 5.38 0 0 0-8.934-5.42ZM11.47 21.075 4.894 14.5h1.963c.051 0 .102-.003.152-.007L12 19.484l4.988-4.985h2.122l-6.58 6.576a.75.75 0 0 1-1.06 0Z" fill="#000000"/>
                    <path d="M9.42 8.414a.75.75 0 0 0-1.348.015l-1.69 3.57H2.75a.75.75 0 0 0 0 1.5h4.107a.75.75 0 0 0 .678-.429l1.234-2.606 2.56 5.12a.75.75 0 0 0 1.279.105l2.698-3.736 1.13 1.29A.75.75 0 0 0 17 13.5h4.25a.75.75 0 0 0 0-1.5h-3.91l-1.526-1.743a.75.75 0 0 0-1.172.054l-2.525 3.496-2.696-5.392Z" fill="#000000"/>
                </svg>Saúde</a>
                </li>
                <li><a href="">
                    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path d="M9.909 3.7a3.875 3.875 0 0 1 4.182 0l8.064 5.169a.75.75 0 0 1 .005 1.259L19 12.193v5.557a.75.75 0 0 1-.15.45l-.001.001-.001.002-.003.004-.009.01-.015.02a7.428 7.428 0 0 1-1.662 1.401C16.036 20.33 14.339 21 12 21s-4.036-.67-5.159-1.361a7.427 7.427 0 0 1-1.25-.957 5.317 5.317 0 0 1-.316-.33 2.719 2.719 0 0 1-.124-.15L5.15 18.2a.75.75 0 0 1-.15-.45v-5.557l-2-1.307v5.364a.75.75 0 0 1-1.5 0V9.5a.75.75 0 0 1 .358-.64l8.05-5.16Zm4.21 11.681a3.875 3.875 0 0 1-4.238 0L6.5 13.172v4.297a5.934 5.934 0 0 0 1.127.893C8.536 18.92 9.964 19.5 12 19.5s3.464-.58 4.373-1.139a5.935 5.935 0 0 0 1.127-.892v-4.297l-3.38 2.21Zm-.837-10.419c-.781-.5-1.783-.5-2.564 0L3.63 9.506l7.071 4.62c.79.515 1.809.515 2.598 0l7.07-4.62-7.087-4.544Z" fill="#000000"/>
                    </svg>Conteúdo Educativo</a>
                </li>
                <li><a href="">
                    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path d="M17.754 14a2.249 2.249 0 0 1 2.25 2.249v.575c0 .894-.32 1.76-.902 2.438-1.57 1.834-3.957 2.739-7.102 2.739-3.146 0-5.532-.905-7.098-2.74a3.75 3.75 0 0 1-.898-2.435v-.577a2.249 2.249 0 0 1 2.249-2.25h11.501Zm0 1.5H6.253a.749.749 0 0 0-.75.749v.577c0 .536.192 1.054.54 1.461 1.253 1.468 3.219 2.214 5.957 2.214s4.706-.746 5.962-2.214a2.25 2.25 0 0 0 .541-1.463v-.575a.749.749 0 0 0-.749-.75ZM12 2.004a5 5 0 1 1 0 10 5 5 0 0 1 0-10Zm0 1.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z" fill="#000000"/>
                    </svg>Perfil</a>
                </li>
            </ul>
        </nav>
    </section>
    <main class="conteudo">
        {% block conteudo %}
        {% endblock %}
    </main>
</body>
</html>

vida_mais_facil/portal/templates/cadastra-saude.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registre a sua Saúde | Vida + Fácil</title>
</head>
<body>
    <main class="cad-saude">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Cadastrar novo Registro</button>
            <a href="{% url 'dashboard' %}">Pular por enquanto</a>
        </form>
    </main>
</body>
</html>

vida_mais_facil/portal/templates/cadastra-user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Olá Seja Bem-vindo! | Vida + Fácil</title>
</head>
<body>
    <main class="cad-user" enctype="multipart/form-data">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Cadastrar-se</button> 
            <a href="{% url 'login' %}">Já tem uma conta? Entre</a>
        </form>
    </main>
</body>
</html>

vida_mais_facil/portal/templates/dashboard.html
{% extends 'base.html' %}

{% block conteudo %}
{% include 'saude.html' %}
    <aside class="consulta">
        {% for atendimento in atendimentos %}
            <div class="atendimento">
                <div class="infos">
                    <h1>{{ atendimento.titulo }} <span>{{ atendimento.get_emergencia_display }}</span></h1>
                    <h3>{{ atendimento.get_medico_display }} <span>{{ atendimento.especialidade }}</span></h3>
                    <p>{{ atendimento.data_agendamento }} <span> {{ atendimento.hora_agendamento }}</span></p>
                    <p>{{ atendimento.observacao }}</p>
                </div>
                <div class="actions">
                    <a href="{% url 'editar' atendimento.id %}">Editar</a>
                    <a href="{% url 'deletar' atendimento.id %}">Remover</a>
                </div>
            </div>
            {% empty %}
                <h1>Sem atendiementos</h1>
        {% endfor %}
    </aside>
{% endblock %}

vida_mais_facil/portal/templates/deleta_consulta.html
{% extends 'base.html' %}

{% block conteudo %}
    <h1>Você tem certeza que quer deletar a consulta '{{ atendimento.titulo }}'?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Deletar</button>
        <a href="{% url 'dashboard' %}">Voltar à Dashboard</a>
    </form>
{% endblock %}

vida_mais_facil/portal/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bem vindo de volta! | Vida + Fácil</title>
</head>
<body>
    <main class="login">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Login</button>
        </form>
    </main>
</body>
</html>

vida_mais_facil/portal/templates/nova_consulta.html
{% extends 'base.html' %}

{% block conteudo %}
    <main class="consulta">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Salvar</button>
            <a href="{% url 'dashboard' %}">Cancelar</a>
        </form>
    </main>
{% endblock %}